using System.Windows.Forms;
using System;

namespace HospitalManagementSystem.Forms.PatientForms
{
    public partial class AddPatientForm : Form
    {
        private TextBox txtPatientName;
        private TextBox txtSurname;
        private DateTimePicker dateOfBirthPicker;
        private TextBox txtFileNumber;
        private TextBox txtPhoneNumber;
        private TextBox txtEmail;
        private TextBox txtAssignedDoctor;
        private Button btnAddPatient;


        public AddPatientForm()
        {
            InitializeComponent();  // Assuming InitializeComponent is autogenerated and initializes components from the designer.
            InitializeUIComponents();
        }

        private void InitializeUIComponents()
        {
            // Initialize textboxes
            txtPatientName = new TextBox();
            txtPatientName.Name = "txtPatientName";
            txtPatientName.Location = new System.Drawing.Point(150, 50);
            txtPatientName.Size = new System.Drawing.Size(200, 20);

            txtSurname = new TextBox();
            txtSurname.Name = "txtSurname";
            txtSurname.Location = new System.Drawing.Point(150, 80);
            txtSurname.Size = new System.Drawing.Size(200, 20);

            dateOfBirthPicker = new DateTimePicker();
            dateOfBirthPicker.Name = "dateOfBirthPicker";
            dateOfBirthPicker.Location = new System.Drawing.Point(150, 110);
            dateOfBirthPicker.Size = new System.Drawing.Size(200, 20);

            txtFileNumber = new TextBox();
            txtFileNumber.Name = "txtFileNumber";
            txtFileNumber.Location = new System.Drawing.Point(150, 140);
            txtFileNumber.Size = new System.Drawing.Size(200, 20);

            txtPhoneNumber = new TextBox();
            txtPhoneNumber.Name = "txtPhoneNumber";
            txtPhoneNumber.Location = new System.Drawing.Point(150, 170);
            txtPhoneNumber.Size = new System.Drawing.Size(200, 20);

            txtEmail = new TextBox();
            txtEmail.Name = "txtEmail";
            txtEmail.Location = new System.Drawing.Point(150, 200);
            txtEmail.Size = new System.Drawing.Size(200, 20);

            txtAssignedDoctor = new TextBox();
            txtAssignedDoctor.Name = "txtAssignedDoctor";
            txtAssignedDoctor.Location = new System.Drawing.Point(150, 230);
            txtAssignedDoctor.Size = new System.Drawing.Size(200, 20);

            // Initialize button
            btnAddPatient = new Button();
            btnAddPatient.Name = "btnAddPatient";
            btnAddPatient.Text = "Add Patient";
            btnAddPatient.Location = new System.Drawing.Point(150, 260);
            btnAddPatient.Click += btnAddPatient_Click;

            // Add these controls to the form's Controls collection
            Controls.Add(txtPatientName);
            Controls.Add(txtSurname);
            Controls.Add(dateOfBirthPicker);
            Controls.Add(txtFileNumber);
            Controls.Add(txtPhoneNumber);
            Controls.Add(txtEmail);
            Controls.Add(txtAssignedDoctor);
            Controls.Add(btnAddPatient);

            // Add labels
            Controls.Add(new Label { Text = "Name:", Location = new System.Drawing.Point(50, 50) });
            Controls.Add(new Label { Text = "Surname:", Location = new System.Drawing.Point(50, 80) });
            Controls.Add(new Label { Text = "Date of Birth:", Location = new System.Drawing.Point(50, 110) });
            Controls.Add(new Label { Text = "Patient File Number:", Location = new System.Drawing.Point(50, 140) });
            Controls.Add(new Label { Text = "Phone Number:", Location = new System.Drawing.Point(50, 170) });
            Controls.Add(new Label { Text = "Email:", Location = new System.Drawing.Point(50, 200) });
            Controls.Add(new Label { Text = "Assigned Doctor:", Location = new System.Drawing.Point(50, 230) });
        }

        private void btnAddPatient_Click(object sender, EventArgs e)
        {
            // Perform input validation
            if (string.IsNullOrWhiteSpace(txtPatientName.Text) || string.IsNullOrWhiteSpace(txtPhoneNumber.Text))
            {
                MessageBox.Show("Please fill in all required fields.", "Validation Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }


        }

        private void InitializeComponent()
        {
            this.SuspendLayout();
            // 
            // AddPatientForm
            // 
            this.ClientSize = new System.Drawing.Size(500, 350);
            this.Name = "AddPatientForm";
            this.Load += new System.EventHandler(this.AddPatientForm_Load);
            this.ResumeLayout(false);
        }

        private void AddPatientForm_Load(object sender, EventArgs e)
        {

        }
    }
}
