using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using HospitalManagementSystem.Database;


namespace HospitalManagementSystem.Forms.PatientForms
{

    public partial class AddPatientForm : Form
    {
        private TextBox txtPatientName;
        private TextBox txtSurname;
        private DateTimePicker dateOfBirthPicker;
        private TextBox txtFileNumber;
        private TextBox txtPhoneNumber;
        private TextBox txtEmail;
        private TextBox txtAssignedDoctor;
        private PictureBox pictureBox1;
        private PictureBox pictureBox2;
        private Button btnAddPatient;


        public AddPatientForm()
        {
            InitializeComponent(); // Assuming InitializeComponent is autogenerated and initializes components from the designer.
            InitializeUIComponents();
        }

        private void InitializeUIComponents()
        {
            // Initialize textboxes
            txtPatientName = new TextBox();
            txtPatientName.Name = "txtPatientName";
            txtPatientName.Location = new System.Drawing.Point(150, 50);
            txtPatientName.Size = new System.Drawing.Size(200, 20);

            txtSurname = new TextBox();
            txtSurname.Name = "txtSurname";
            txtSurname.Location = new System.Drawing.Point(150, 80);
            txtSurname.Size = new System.Drawing.Size(200, 20);

            dateOfBirthPicker = new DateTimePicker();
            dateOfBirthPicker.Name = "dateOfBirthPicker";
            dateOfBirthPicker.Location = new System.Drawing.Point(150, 110);
            dateOfBirthPicker.Size = new System.Drawing.Size(200, 20);

            txtFileNumber = new TextBox();
            txtFileNumber.Name = "txtFileNumber";
            txtFileNumber.Location = new System.Drawing.Point(150, 140);
            txtFileNumber.Size = new System.Drawing.Size(200, 20);

            txtPhoneNumber = new TextBox();
            txtPhoneNumber.Name = "txtPhoneNumber";
            txtPhoneNumber.Location = new System.Drawing.Point(150, 170);
            txtPhoneNumber.Size = new System.Drawing.Size(200, 20);

            txtEmail = new TextBox();
            txtEmail.Name = "txtEmail";
            txtEmail.Location = new System.Drawing.Point(150, 200);
            txtEmail.Size = new System.Drawing.Size(200, 20);

            txtAssignedDoctor = new TextBox();
            txtAssignedDoctor.Name = "txtAssignedDoctor";
            txtAssignedDoctor.Location = new System.Drawing.Point(150, 230);
            txtAssignedDoctor.Size = new System.Drawing.Size(200, 20);

            // Initialize pictureBox1 (hospital logo) at the bottom right
            pictureBox1 = new PictureBox();
            pictureBox1.Name = "pictureBox1";
            pictureBox1.Location = new System.Drawing.Point(500, 320); // Adjust the appropriate location
            pictureBox1.Size = new System.Drawing.Size(150, 75); // Adjust the appropriate size
            pictureBox1.SizeMode = PictureBoxSizeMode.StretchImage;
            pictureBox1.Image = Image.FromFile(Path.Combine("C:\\Users\\user\\Desktop\\Project\\Resources", "hospital logo.png"));
            // ... (additional properties for pictureBox1)

            // Initialize pictureBox2 (patient logo) to the right of input fields
            pictureBox2 = new PictureBox();
            pictureBox2.Name = "pictureBox2";
            pictureBox2.Location = new System.Drawing.Point(440, 80); // Adjust the appropriate location
            pictureBox2.Size = new System.Drawing.Size(150, 130); // Adjust the appropriate size
            pictureBox2.SizeMode = PictureBoxSizeMode.StretchImage;
            pictureBox2.Image = Image.FromFile(Path.Combine("C:\\Users\\user\\Desktop\\Project\\Resources", "patient logo.jpg"));
            // ... (additional properties for pictureBox2)

            // Initialize button in the center and a bit below
            btnAddPatient = new Button();
            btnAddPatient.Name = "btnAddPatient";
            btnAddPatient.Text = "Add Patient";
            btnAddPatient.Location = new System.Drawing.Point(150, 300); // Adjust the button location
            btnAddPatient.Click += btnAddPatient_Click;
            btnAddPatient.Size = new System.Drawing.Size(150, 40); // Set the appropriate size
            btnAddPatient.BackColor = System.Drawing.Color.FromArgb(0, 123, 255);
            btnAddPatient.ForeColor = System.Drawing.Color.White;
            btnAddPatient.Font = new System.Drawing.Font("Open Sans", 12, System.Drawing.FontStyle.Bold);
            btnAddPatient.FlatStyle = FlatStyle.Flat;
            btnAddPatient.FlatAppearance.BorderSize = 0;



            // Add these controls to the form's Controls collection
            Controls.Add(txtPatientName);
            Controls.Add(txtSurname);
            Controls.Add(dateOfBirthPicker);
            Controls.Add(txtFileNumber);
            Controls.Add(txtPhoneNumber);
            Controls.Add(txtEmail);
            Controls.Add(txtAssignedDoctor);
            Controls.Add(btnAddPatient);
            Controls.Add(pictureBox1);
            Controls.Add(pictureBox2);

            // Add labels
            Controls.Add(new Label { Text = "Name:", Location = new System.Drawing.Point(50, 50) });
            Controls.Add(new Label { Text = "Surname:", Location = new System.Drawing.Point(50, 80) });
            Controls.Add(new Label { Text = "Date of Birth:", Location = new System.Drawing.Point(50, 110) });
            Controls.Add(new Label { Text = "Patient File Number:", Location = new System.Drawing.Point(50, 140) });
            Controls.Add(new Label { Text = "Phone Number:", Location = new System.Drawing.Point(50, 170) });
            Controls.Add(new Label { Text = "Email:", Location = new System.Drawing.Point(50, 200) });
            Controls.Add(new Label { Text = "Assigned Doctor:", Location = new System.Drawing.Point(50, 230) });
        }

        private void btnAddPatient_Click(object sender, EventArgs e)
        {
            // Perform input validation
            if (string.IsNullOrWhiteSpace(txtPatientName.Text) || string.IsNullOrWhiteSpace(txtPhoneNumber.Text))
            {
                MessageBox.Show("Please fill in all required fields.", "Validation Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            // Create a new patient object with the form data
            var newPatient = new Patient
            {
                Name = txtPatientName.Text,
                Surname = txtSurname.Text,
                DateOfBirth = dateOfBirthPicker.Value,
                FileNumber = txtFileNumber.Text,
                PhoneNumber = txtPhoneNumber.Text,
                Email = txtEmail.Text,
                AssignedDoctor = txtAssignedDoctor.Text
            };

            try
            {
                // Save the new patient to the database
                using (var dbContext = new YourDbContext())
                {
                    dbContext.Patients.Add(newPatient);
                    dbContext.SaveChanges();
                }

                // Display success message
                MessageBox.Show("Patient added successfully.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex)
            {
                // Log or display detailed error information
                MessageBox.Show($"An error occurred: {ex.Message}\n\nInner Exception: {ex.InnerException?.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }

        }

        private void InitializeComponent()
        {
            this.SuspendLayout();
            // 
            // AddPatientForm
            // 
            this.ClientSize = new System.Drawing.Size(650, 400);
            this.Name = "AddPatientForm";
            this.Load += new System.EventHandler(this.AddPatientForm_Load);
            this.ResumeLayout(false);

        }

        private void AddPatientForm_Load(object sender, EventArgs e)
        {

        }


    }

}